<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="connectors" nsURI="https://gov.ornl.doecode.connectors.ecore"
    nsPrefix="gov.ornl.doecode.connectors">
  <eClassifiers xsi:type="ecore:EClass" name="TestClass"/>
</ecore:EPackage>
